#!/usr/bin/env python3
"""Generate winget manifests from a published stable release's signed checksums."""
import argparse
import datetime
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

REPOSITORY = "anydoor7/tslink"
IDENTIFIER = "anydoor7.TSLink"
MANIFEST_VERSION = "1.12.0"


def stable_version(tag):
    if not re.fullmatch(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", tag):
        raise ValueError("Use a stable vMAJOR.MINOR.PATCH tag without prerelease or build metadata")
    return tag[1:]


def windows_hashes(checksums, version):
    entries = {}
    for line in checksums.splitlines():
        match = re.fullmatch(r"([0-9a-fA-F]{64})\s+\*?([^\s]+)", line)
        if not match:
            raise ValueError("Malformed checksums.txt entry")
        digest, name = match.groups()
        if name in entries:
            raise ValueError("Duplicate checksums.txt entry: " + name)
        entries[name] = digest.lower()
    hashes = {}
    for architecture, suffix in (("arm64", "arm64"), ("x64", "amd64")):
        name = f"tslink_{version}_windows_{suffix}.zip"
        if name not in entries:
            raise ValueError("checksums.txt is missing " + name)
        hashes[architecture] = entries[name]
    return hashes


def render(tag, checksums, release_date):
    version = stable_version(tag)
    hashes = windows_hashes(checksums, version)
    # Use the release's publication date, never the local generation date.
    datetime.date.fromisoformat(release_date)

    def header(kind):
        return ("# This file was generated by winget-manifests.py. DO NOT EDIT.\n"
                f"# yaml-language-server: $schema=https://aka.ms/winget-manifest.{kind}.{MANIFEST_VERSION}.schema.json\n"
                f"PackageIdentifier: {IDENTIFIER}\nPackageVersion: {version}\n")

    installer = header("installer") + (
        "InstallerLocale: en-US\nInstallerType: zip\n"
        f'ReleaseDate: "{release_date}"\nInstallers:\n'
    )
    for architecture, suffix in (("arm64", "arm64"), ("x64", "amd64")):
        installer += (
            f"  - Architecture: {architecture}\n"
            "    NestedInstallerType: portable\n"
            "    NestedInstallerFiles:\n"
            "      - RelativeFilePath: tslink.exe\n"
            "        PortableCommandAlias: tslink\n"
            f"    InstallerUrl: https://github.com/{REPOSITORY}/releases/download/{tag}/tslink_{version}_windows_{suffix}.zip\n"
            f"    InstallerSha256: {hashes[architecture]}\n"
            "    UpgradeBehavior: uninstallPrevious\n"
        )
    installer += f"ManifestType: installer\nManifestVersion: {MANIFEST_VERSION}\n"
    locale = header("defaultLocale") + (
        "PackageLocale: en-US\nPublisher: anydoor7\nPackageName: TSLink\n"
        f"PackageUrl: https://github.com/{REPOSITORY}\nLicense: Apache-2.0\n"
        f"LicenseUrl: https://github.com/{REPOSITORY}/blob/{tag}/LICENSE\n"
        "ShortDescription: Give each local app a private Tailscale address and control who can reach it\n"
        "Moniker: tslink\n"
        f"ReleaseNotesUrl: https://github.com/{REPOSITORY}/releases/tag/{tag}\n"
        "InstallationNotes: After upgrading, run tslink install again if TSLink runs as a background service.\n"
        f"ManifestType: defaultLocale\nManifestVersion: {MANIFEST_VERSION}\n"
    )
    version_manifest = header("version") + (
        f"DefaultLocale: en-US\nManifestType: version\nManifestVersion: {MANIFEST_VERSION}\n"
    )
    return {f"{IDENTIFIER}.installer.yaml": installer,
            f"{IDENTIFIER}.locale.en-US.yaml": locale,
            f"{IDENTIFIER}.yaml": version_manifest}


def generate(tag, out, allow_unverified=False):
    version = stable_version(tag)
    cosign = shutil.which("cosign")
    if cosign is None and not allow_unverified:
        raise ValueError("cosign is required; use --allow-unverified explicitly for local inspection only")
    release = json.loads(subprocess.check_output([
        "gh", "release", "view", tag, "--repo", REPOSITORY,
        "--json", "tagName,isDraft,isPrerelease,publishedAt",
    ], text=True))
    if release["tagName"] != tag or release["isDraft"] or release["isPrerelease"]:
        raise ValueError("The tag must identify a published stable release")
    with tempfile.TemporaryDirectory(prefix="tslink-winget-") as scratch:
        download = ["gh", "release", "download", tag, "--repo", REPOSITORY,
                    "--dir", scratch, "--pattern", "checksums.txt"]
        if cosign:
            download += ["--pattern", "checksums.txt.sigstore.json"]
        subprocess.run(download, check=True)
        checksums = Path(scratch) / "checksums.txt"
        if cosign:
            subprocess.run([
                cosign, "verify-blob", str(checksums),
                "--bundle", str(checksums) + ".sigstore.json",
                "--certificate-identity",
                f"https://github.com/{REPOSITORY}/.github/workflows/release.yml@refs/tags/{tag}",
                "--certificate-oidc-issuer", "https://token.actions.githubusercontent.com",
            ], check=True)
        else:
            print("WARNING: checksums are unverified (--allow-unverified); do not submit these files", file=sys.stderr)
        manifests = render(tag, checksums.read_text(encoding="utf-8"), release["publishedAt"][:10])
    destination = Path(out) / "manifests/a/anydoor7/TSLink" / version
    destination.mkdir(parents=True, exist_ok=True)
    for name, body in manifests.items():
        (destination / name).write_text(body, encoding="utf-8")
    print(destination)
    return destination


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tag")
    parser.add_argument("--out", type=Path, default=Path("winget-manifests"))
    parser.add_argument("--allow-unverified", action="store_true")
    args = parser.parse_args()
    try:
        generate(args.tag, args.out, args.allow_unverified)
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"winget manifest generation failed: {error}\n")


if __name__ == "__main__":
    main()
