// Command check-manifest-platforms compares manifests generated by native
// Darwin, Linux, and Windows binaries. It verifies both directions of the live
// Cobra flag contract: every structurally divergent (command path, flag name)
// entry is marked with its exact GOOS set, and every mark describes a real
// divergence. JSON result-field scope is prose-defined rather than build-tree
// divergence and is pinned separately by cmd manifest tests.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/monody0007/tslink/cmd"
)

var comparedGOOS = cmd.SupportedManifestPlatforms()

type flagKey struct {
	CommandPath string
	FlagName    string
}

type flagOccurrence struct {
	present map[string]bool
	marks   map[string][]string
}

func main() {
	darwinPath := flag.String("darwin", "", "path to a manifest generated on Darwin")
	linuxPath := flag.String("linux", "", "path to a manifest generated on Linux")
	windowsPath := flag.String("windows", "", "path to a manifest generated on Windows")
	flag.Parse()

	paths := map[string]string{
		"darwin":  *darwinPath,
		"linux":   *linuxPath,
		"windows": *windowsPath,
	}
	manifests := make(map[string]cmd.CLIManifest, len(paths))
	for _, goos := range comparedGOOS {
		path := paths[goos]
		if path == "" {
			fmt.Fprintf(os.Stderr, "check-manifest-platforms: -%s is required\n", goos)
			os.Exit(1)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "check-manifest-platforms: read %s manifest: %v\n", goos, err)
			os.Exit(1)
		}
		var manifest cmd.CLIManifest
		if err := json.Unmarshal(data, &manifest); err != nil {
			fmt.Fprintf(os.Stderr, "check-manifest-platforms: decode %s manifest: %v\n", goos, err)
			os.Exit(1)
		}
		manifests[goos] = manifest
	}

	count, err := verifyPlatformFlagMarks(manifests)
	if err != nil {
		fmt.Fprintln(os.Stderr, "check-manifest-platforms:", err)
		os.Exit(1)
	}
	fmt.Printf("check-manifest-platforms: verified %d platform-scoped flag entries across %s\n", count, strings.Join(comparedGOOS, ", "))
}

func verifyPlatformFlagMarks(manifests map[string]cmd.CLIManifest) (int, error) {
	observed := map[flagKey]*flagOccurrence{}
	var referenceCommands []string
	for index, goos := range comparedGOOS {
		manifest, ok := manifests[goos]
		if !ok {
			return 0, fmt.Errorf("missing %s manifest", goos)
		}
		if manifest.SchemaVersion != 2 {
			return 0, fmt.Errorf("%s manifest schema_version = %d, want 2", goos, manifest.SchemaVersion)
		}
		if manifest.Platform.GOOS != goos {
			return 0, fmt.Errorf("%s artifact declares platform.goos %q", goos, manifest.Platform.GOOS)
		}

		commandSeen := map[string]bool{}
		var commands []string
		for _, command := range manifest.Commands {
			if commandSeen[command.Path] {
				return 0, fmt.Errorf("%s manifest repeats command path %q", goos, command.Path)
			}
			commandSeen[command.Path] = true
			commands = append(commands, command.Path)
			flagSeen := map[string]bool{}
			for _, manifestFlag := range command.Flags {
				if flagSeen[manifestFlag.Name] {
					return 0, fmt.Errorf("%s manifest repeats %s --%s", goos, command.Path, manifestFlag.Name)
				}
				flagSeen[manifestFlag.Name] = true
				key := flagKey{CommandPath: command.Path, FlagName: manifestFlag.Name}
				entry := observed[key]
				if entry == nil {
					entry = &flagOccurrence{present: map[string]bool{}, marks: map[string][]string{}}
					observed[key] = entry
				}
				entry.present[goos] = true
				if manifestFlag.Platforms != nil {
					normalized, err := normalizePlatformSet(manifestFlag.Platforms)
					if err != nil {
						return 0, fmt.Errorf("%s %s --%s mark: %w", goos, command.Path, manifestFlag.Name, err)
					}
					entry.marks[goos] = normalized
				}
			}
		}
		sort.Strings(commands)
		if index == 0 {
			referenceCommands = commands
		} else if strings.Join(commands, "\x00") != strings.Join(referenceCommands, "\x00") {
			return 0, fmt.Errorf("command identities differ on %s: got %v, want %v", goos, commands, referenceCommands)
		}
	}

	keys := make([]flagKey, 0, len(observed))
	for key := range observed {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].CommandPath != keys[j].CommandPath {
			return keys[i].CommandPath < keys[j].CommandPath
		}
		return keys[i].FlagName < keys[j].FlagName
	})

	divergent := 0
	for _, key := range keys {
		entry := observed[key]
		actual := presentPlatforms(entry.present)
		if len(actual) == len(comparedGOOS) {
			if len(entry.marks) != 0 {
				return 0, fmt.Errorf("stale mark on %s --%s: entry exists on all platforms", key.CommandPath, key.FlagName)
			}
			continue
		}
		divergent++
		for _, goos := range actual {
			declared, ok := entry.marks[goos]
			if !ok {
				return 0, fmt.Errorf("unmarked platform-specific entry %s --%s: actual platforms %v", key.CommandPath, key.FlagName, actual)
			}
			if strings.Join(declared, "\x00") != strings.Join(actual, "\x00") {
				return 0, fmt.Errorf("incorrect mark on %s --%s in %s manifest: declared %v, actual %v", key.CommandPath, key.FlagName, goos, declared, actual)
			}
		}
	}
	return divergent, nil
}

func normalizePlatformSet(platforms []string) ([]string, error) {
	if len(platforms) == 0 {
		return nil, fmt.Errorf("platforms must be non-empty when present")
	}
	known := make(map[string]bool, len(cmd.SupportedManifestPlatforms()))
	for _, goos := range cmd.SupportedManifestPlatforms() {
		known[goos] = true
	}
	seen := map[string]bool{}
	normalized := append([]string(nil), platforms...)
	for _, goos := range normalized {
		if !known[goos] {
			return nil, fmt.Errorf("unsupported GOOS %q", goos)
		}
		if seen[goos] {
			return nil, fmt.Errorf("duplicate GOOS %q", goos)
		}
		seen[goos] = true
	}
	sort.Strings(normalized)
	return normalized, nil
}

func presentPlatforms(present map[string]bool) []string {
	var platforms []string
	for _, goos := range comparedGOOS {
		if present[goos] {
			platforms = append(platforms, goos)
		}
	}
	return platforms
}
